<?xml version="1.0" encoding="utf-8"?><Database Name="LINQ" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=CADAVILES08\SQLEXPRESS02;Initial Catalog=LINQ;Integrated Security=True" SettingsObjectName="HUCANET.Properties.Settings" SettingsPropertyName="LINQConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Enfermo" Member="Enfermo">
    <Type Name="Enfermo">
      <Column Name="inscripcion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Apellido" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Dir" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fecha_Nac" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="S" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="NSS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cod_Hospital" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Hospital_Enfermo" Member="Hospital" ThisKey="Cod_Hospital" OtherKey="Hospital_cod" Type="Hospital" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Doctor" Member="Doctor">
    <Type Name="Doctor">
      <Column Name="Hospital_Cod" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Doctor_No" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Apellido" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Especialidad" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Hospital_Doctor" Member="Hospital" ThisKey="Hospital_Cod" OtherKey="Hospital_cod" Type="Hospital" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Sala" Member="Sala">
    <Type Name="Sala">
      <Column Name="Sala_Cod" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cod_Hospital" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Especialidad" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Hospital_Sala" Member="Hospital" ThisKey="Cod_Hospital" OtherKey="Hospital_cod" Type="Hospital" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Hospital" Member="Hospital">
    <Type Name="Hospital">
      <Column Name="Hospital_cod" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="num_cama" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Hospital_Enfermo" Member="Enfermo" ThisKey="Hospital_cod" OtherKey="Cod_Hospital" Type="Enfermo" />
      <Association Name="Hospital_Doctor" Member="Doctor" ThisKey="Hospital_cod" OtherKey="Hospital_Cod" Type="Doctor" />
      <Association Name="Hospital_Sala" Member="Sala" ThisKey="Hospital_cod" OtherKey="Cod_Hospital" Type="Sala" />
    </Type>
  </Table>
  <Function Name="dbo.SP_InsertaEnfermo" Method="SP_InsertaEnfermo">
    <Parameter Name="inscripcion" Type="System.Int32" DbType="Int" />
    <Parameter Name="Apellido" Parameter="apellido" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Direccion" Parameter="direccion" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Fecha_Nac" Parameter="fecha_Nac" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="S" Parameter="s" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="NSS" Parameter="nSS" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_EliminarEnfermo" Method="SP_EliminarEnfermo">
    <Parameter Name="inscripcion" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_MostrarEnfermo" Method="SP_MostrarEnfermo">
    <Parameter Name="inscripcion" Type="System.Int32" DbType="Int" />
    <Parameter Name="Apellido" Parameter="apellido" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Direccion" Parameter="direccion" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Fecha_Nac" Parameter="fecha_Nac" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="S" Parameter="s" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="NSS" Parameter="nSS" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_MostrarEnfermoResult">
      <Column Name="inscripcion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Apellido" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Dir" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fecha_Nac" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="S" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="NSS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cod_Hospital" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_ListarEnfermo" Method="SP_ListarEnfermo">
    <ElementType Name="SP_ListarEnfermoResult">
      <Column Name="inscripcion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Apellido" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Dir" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fecha_Nac" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="S" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="NSS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cod_Hospital" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_ModificarEnferno" Method="SP_ModificarEnferno">
    <Parameter Name="inscripcion" Type="System.Int32" DbType="Int" />
    <Parameter Name="Apellido" Parameter="apellido" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Direccion" Parameter="direccion" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Fecha_Nac" Parameter="fecha_Nac" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="S" Parameter="s" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="NSS" Parameter="nSS" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_ListarDoctor" Method="SP_ListarDoctor">
    <ElementType Name="SP_ListarDoctorResult">
      <Column Name="Hospital_Cod" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Doctor_No" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Apellido" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Especialidad" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_InsertaDoctor" Method="SP_InsertaDoctor">
    <Parameter Name="Hospital_Cod" Parameter="hospital_Cod" Type="System.Int32" DbType="Int" />
    <Parameter Name="Doctor_No" Parameter="doctor_No" Type="System.Int32" DbType="Int" />
    <Parameter Name="Apellido" Parameter="apellido" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Especialidad" Parameter="especialidad" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_EliminarDoctor" Method="SP_EliminarDoctor">
    <Parameter Name="Doctor_No" Parameter="doctor_No" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_InsertaSala" Method="SP_InsertaSala">
    <Parameter Name="Sala_Cod" Parameter="sala_Cod" Type="System.Int32" DbType="Int" />
    <Parameter Name="Cod_Hospital" Parameter="cod_Hospital" Type="System.Int32" DbType="Int" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Especialidad" Parameter="especialidad" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_ListarSala" Method="SP_ListarSala">
    <ElementType Name="SP_ListarSalaResult">
      <Column Name="Sala_Cod" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cod_Hospital" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Especialidad" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_ModificarSala" Method="SP_ModificarSala">
    <Parameter Name="Sala_Cod" Parameter="sala_Cod" Type="System.Int32" DbType="Int" />
    <Parameter Name="Cod_Hospital" Parameter="cod_Hospital" Type="System.Int32" DbType="Int" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Especialidad" Parameter="especialidad" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_EliminarSala" Method="SP_EliminarSala">
    <Parameter Name="Sala_Cod" Parameter="sala_Cod" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_ModificarDoctor" Method="SP_ModificarDoctor1">
    <Parameter Name="Hospital_Cod" Parameter="hospital_Cod" Type="System.Int32" DbType="Int" />
    <Parameter Name="Doctor_No" Parameter="doctor_No" Type="System.Int32" DbType="Int" />
    <Parameter Name="Apellido" Parameter="apellido" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Especialidad" Parameter="especialidad" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_CodigosHosp" Method="SP_CodigosHosp">
    <ElementType Name="SP_CodigosHospResult">
      <Column Name="Hospital_cod" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>