<?xml version="1.0" encoding="utf-8"?><Database Name="LINQ" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=CADAVILES08\SQLEXPRESS02;Initial Catalog=LINQ;Integrated Security=True" SettingsObjectName="Alumnos.Properties.Settings" SettingsPropertyName="LINQConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ALUMNOS" Member="ALUMNOS">
    <Type Name="ALUMNOS">
      <Column Name="codigo" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="dni" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="turno" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="sexo" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="repetidor" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="modulo" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="especialidad" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
    </Type>
  </Table>
</Database>